---
title: "Data Final Project"
author: "Alex LaPolice"
date: "11/5/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)


```


```{r}


Jules <- read_csv("legacy_data/game_player_stats/game_receiving_df.csv") %>%
  filter(Team == "NE") %>%
  filter(Player_Name == "J.Edelman") 

#This is NFL Data that I have broken down to recieving data for Julian Edelman on the New England Patriots. I would like to explore something that involves how Julian Edelman's success effects the succes of the team as a whole. 
```


```{r, include=FALSE, echo=FALSE}
summary(Jules)
```

#Average targets by Season progression
```{r}
Jules %>%
  mutate(Season = str_sub(GameID, 1, 4)) %>%
  group_by(Season) %>%
  summarize(Avg_Targets = mean(Targets))

#through his first 4 seasons he only averaged, at most 4 targets a game, but since 2013 he has averaged at least 9 targets/game demonstrating progression and potentially an improved confidence from Brady
```
#AVG Yards by opponent
```{r}
Jules %>%
  group_by(Opponent) %>%
  summarize(Avg_Yards = mean(Total_Yards)) %>%
  filter(Avg_Yards >= 70)


#On Avg his top 5 most favorable matchups are DAL, LA, SD, SEA, and DET
#His closest divisional oponent is MIA at 73 yards/game, No other divisional opponents in tops 10
```


#YARDAGE/Game by Season progression
```{r}
Jules %>%
  mutate(Season = str_sub(GameID, 1, 4)) %>%
  group_by(Season) %>%
  summarize(Avg_Yards = mean(Total_Yards))

#same as with targets, his yardage spiked in 2013 by ~ 40 yards/game

```

